GET {{ExceptionHandling_HostAddress}}/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTJkMTBlMS0wNDc4LTRiNzYtOWIxMC1mNDhmYTI4NDQ2OGQiLCJlbWFpbCI6ImFsbGVuQGdtYWlsLmNvbSIsImV4cCI6MTc1ODA5OTA2MCwiaXNzIjoiRXhjZXB0aW9uSGFuZGxpbmciLCJhdWQiOiJFeGNlcHRpb25IYW5kbGluZyJ9.W-dXbWr549jrrh4D1skq4zRMKEcLZ2Hvh41KhIh--dY
