GET https://localhost:7020/api/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTJkMTBlMS0wNDc4LTRiNzYtOWIxMC1mNDhmYTI4NDQ2OGQiLCJlbWFpbCI6ImFsbGVuQGdtYWlsLmNvbSIsImV4cCI6MTc1ODA0MTk5NSwiaXNzIjoiRXhjZXB0aW9uSGFuZGxpbmciLCJhdWQiOiJFeGNlcHRpb25IYW5kbGluZyJ9.3F5dmoJVDcEIJcUlIvdjq1iwFi7XH87RSihojGCwJqc
